Add -f to force a downgrade which will add reindex, few other tweaks

diff --git a/trc-updater b/trc-updater
--- a/trc-updater
+++ b/trc-updater
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-current_vers=120108
-vers="0.12.1"
+install_vers=0.12.1.8
+
 downloaded=0
 tmpdir=$(mktemp -d)
 
@@ -29,6 +29,13 @@ if [ $arch != "x86_64" ]; then
 	arch="i686-pc";
 fi
 
+vers_major=$(echo ${install_vers} | cut -d. -f1)
+vers_minor=$(echo ${install_vers} | cut -d. -f2)
+vers_micro=$(echo ${install_vers} | cut -d. -f3)
+vers_build=$(echo ${install_vers} | cut -d. -f4)
+printf -v current_vers "%02d%02d%02d" $vers_minor $vers_micro $vers_build
+vers="${vers_major}.${vers_minor}.${vers_micro}"
+
 url=https://terracoin.io/bin/terracoin-core-current/terracoin-${vers}-${arch}-linux-gnu.tar.gz
 
 myuid=$(id -u)
@@ -37,6 +44,12 @@ pids=$(ps auxwww | grep terracoind | grep -v grep | grep -v testnet | awk {'prin
 if [ $(echo ${pids} | wc -w) -lt 1 ]; then
 	echo "terracoind not found running!"
 	exit
+fi
+
+force=0
+if [ ! -z $1 ] && [ "$1" == "-f" ]; then
+	echo "Enabling downgrading"
+	force=1
 fi
 
 for pid in ${pids}; do
@@ -67,7 +80,10 @@ for pid in ${pids}; do
 		cmdprefix="sudo -u #${runas} "
 	fi
 
+	newstart=0
 	cmd=$(cat /proc/${pid}/cmdline | tr '\000' ' ')
+        cleancmd=$(echo ${cmd} | sed -e 's/-reindex//g')
+	reindexcmd="${cleancmd} -reindex"
 	exe=$(${cmdprefix}realpath /proc/${pid}/exe)
 	cwd=$(${cmdprefix}realpath /proc/${pid}/cwd)
 
@@ -115,9 +131,21 @@ for pid in ${pids}; do
 		if [ ${terracoincli_uid} -ne ${myuid} ]; then 
 			terracoincliprefix="sudo -u #${terracoincli_uid} "
 		fi
-		terracoind_vers=$(${cmdprefix}${terracoincli_dir}/terracoin-cli getinfo | grep '"version"' | cut -d: -f2 | tr -d " " | tr -d ",")
-		if [[ ${terracoind_vers} -ge ${current_vers} ]]; then
-			echo "terracoind already updated!"
+		terracoind_vers=$(${cmdprefix}${terracoincli_dir}/terracoin-cli getinfo 2>/dev/null | grep '"version"' | cut -d: -f2 | tr -d " " | tr -d ",")
+		if [[ ${terracoind_vers} -eq ${current_vers} ]]; then
+			echo "terracoind already at current version!"
+			continue
+		elif [[ ${terracoind_vers} -gt ${current_vers} ]] && [ ${force} -ne 1 ]; then
+			echo "terracoind already at newer then requested, to force please rerun with -f"
+			continue
+		elif [[ ${terracoind_vers} -gt ${current_vers} ]] && [ ${force} -eq 1 ]; then
+			echo "terracoind is newer, downgrading (will take long as reindex is enabled)"
+		fi
+	fi
+	if [ ${terracoind_vers} == 0 ]; then
+		read -p "Could not detect current running version, continue?" -n 1 -r
+		echo
+		if ! [[ $REPLY =~ ^[yY]$ ]]; then
 			continue
 		fi
 	fi
@@ -169,10 +197,11 @@ for pid in ${pids}; do
 	echo "OK"
 
 	echo -n "Updating terracoind... "
-	${terracoindprefix}cp ${tmpdir}/bin/terracoind ${terracoind_dir}
+	${terracoindprefix}cp ${tmpdir}/bin/terracoind ${terracoind_dir} 2>/dev/null
 	if [ $? -ne 0 ]; then
-		echo "FAILED ($?)"
+		echo "FAILED ($?), this is likely do to having 2 copies running on the same system, close one and rerun!"
 	else
+		newstart=1
 		echo "OK"
 		if [ ${terracoincli_found} -eq 1 ]; then
 			echo -n "Updating terracoin-cli... "
@@ -186,6 +215,13 @@ for pid in ${pids}; do
 	fi
 
 	echo -n "Restarting terracoind... "
+	if [[ ${newstart} -eq 1 ]]; then
+		if [[ ${force} -eq 1 ]] && [[ ${cmd} != *"-reindex"* ]]; then
+			cmd=${reindexcmd}
+		else
+			cmd=${cleancmd}
+		fi
+	fi
 	su - ${runasun} -c "cd ${cwd} && ${cmd} &" > /dev/null 2>&1
 	if [ $? -ne 0 ]; then
 		echo "FAILED ($?), Please restart it by hand"
